apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: myNginxPod
spec:
  containers:
  - name: nginxContainer
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000