spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        - id: OddDate_route
          uri: https://google.com
          predicates:
            - Path=/odd/**
            - OddDate=true
        - id: EvenDate_route
          uri: https://duckduckgo.com
          predicates:
            - Path=/odd/**
            - OddDate=false
        - id: WeatherInGalway
          uri: https://www.google.com/url?sa=i&url=https%3A%2F%2Fgiphy.com%2Fexplore%2Frain-animated&psig=AOvVaw0YBkFTbWEaprMYKGW2vZ1L&ust=1675116145405000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCJiqg4jk7fwCFQAAAAAdAAAAABAE
          predicates:
            - Path=/weather/**
            - Weather=Galway