server:
  port: 8081
  servlet:
    context-path: /resource-server

spring:
  application:
    name: jwt
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
