name: Build Bitbucket Client
run-name: ${{ github.actor }} pushed code to Bitbucket Client folder 🚀
on: 
  push:
    paths:
      - java/bitbucket-client/**
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f java/bitbucket-client/pom.xml clean resources:resources generate-sources
