spring:
  application:
    name: data
  datasource:
    #url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MySQL  # In-memory H2
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    #password: password # You may want to change this
  # SQLite Configuration
    sqlite:
      url: jdbc:sqlite:/sqlite.db  # Path to your SQLite file
      driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # Optional: Show SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 dialect
  h2:
    console:
      enabled: true # Enable the H2 console (access via http://localhost:8080/h2-console)
      path: /h2-console # Customize if needed


app:
  api:
    cors:
      allowedOrigins: http://localhost:4200
      allowedMethods: GET,POST,PUT,DELETE
      #allowedHeaders: Content-Type,Authorization
      allowedHeaders: \*
