spring:
  application:
    name: data
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MySQL  # In-memory H2
    driver-class-name: org.h2.Driver
    username: sa
    password: password # You may want to change this
  jpa:
    hibernate:
      ddl-auto: create-drop # Creates and drops tables on each run. Use 'update' for production
    show-sql: true # Optional: Show SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2 dialect
  h2:
    console:
      enabled: true # Enable the H2 console (access via http://localhost:8080/h2-console)
      path: /h2-console # Customize if needed
